// require('jquery/dist/jquery.min');
// require('admin-panel/files/assets/js/jquery/js/jquery.min');
// require('bootstrap/dist/js/bootstrap.min');
require('admin-panel/files/assets/js/jquery-ui/js/jquery-ui.min');
require('admin-panel/files/assets/js/popper.js/js/popper.min');
// require('jquery-slimscroll/jquery.slimscroll');
// require('admin-panel/files/assets/js/jquery-slimscroll/js/jquery.slimscroll');
// require('admin-panel/files/assets/js/script');
// require('admin-panel/files/assets/js/modernizr/js/modernizr');
// require('admin-panel/files/assets/js/modernizr/js/css-scrollbars');
// require('admin-panel/files/assets/js/pcoded.min');
// require('admin-panel/files/assets/js/vartical-layout.min');
// require('admin-panel/files/assets/js/jquery.mCustomScrollbar.concat.min');
// require('admin-panel/files/assets/js/jquery-slimscroll/js/jquery.slimscroll');
// require('admin-panel/files/assets/js/modernizr/js/modernizr');
// require('admin-panel/files/assets/js/modernizr/js/css-scrollbars');
// require('admin-panel/files/assets/js/i18next/js/i18next.min');
// require('admin-panel/files/assets/js/i18next-xhr-backend/js/i18nextXHRBackend.min');
// require('admin-panel/files/assets/js/jquery-i18next/js/jquery-i18next.min');
// require('admin-panel/files/assets/js/pcoded.min');
// require('admin-panel/files/assets/js/vartical-layout.min');
// // require('admin-panel/files/assets/js/jquery.mCustomScrollbar.concat.min');
// require('admin-panel/files/assets/js/script');
// require('admin-panel/files/assets/js/i18next-browser-languagedetector/js/i18nextBrowserLanguageDetector.min');

// datatable
// require('admin-panel/files/assets/js/datatables.net/js/jquery.dataTables.min');
// require('admin-panel/files/assets/js/datatables.net-buttons/js/dataTables.buttons.min');
// require('admin-panel/files/assets/js/datatables.net-buttons/js/buttons.print.min');
// require('admin-panel/files/assets/pages/data-table/js/jszip.min');
// require('admin-panel/files/assets/pages/data-table/js/pdfmake.min');
// require('admin-panel/files/assets/pages/data-table/js/vfs_fonts');
// require('admin-panel/files/assets/pages/data-table/extensions/buttons/js/buttons.flash.min');
// require('admin-panel/files/assets/pages/data-table/extensions/buttons/js/jszip.min');
// require('admin-panel/files/assets/pages/data-table/extensions/buttons/js/vfs_fonts');
// require('admin-panel/files/assets/pages/data-table/extensions/buttons/js/buttons.colVis.min');
// require('admin-panel/files/assets/js/datatables.net-buttons/js/buttons.print.min');
// require('admin-panel/files/assets/js/datatables.net-buttons/js/buttons.html5.min');
// require('admin-panel/files/assets/js/datatables.net-bs4/js/dataTables.bootstrap4.min');
// require('admin-panel/files/assets/js/datatables.net-responsive/js/dataTables.responsive.min');
// require('admin-panel/files/assets/js/datatables.net-responsive-bs4/js/responsive.bootstrap4.min');
// require('admin-panel/files/assets/pages/data-table/extensions/buttons/js/extension-btns-custom');
// require('admin-panel/files/assets/pages/data-table/extensions/buttons/js/dataTables.buttons.min');
